# Clippy configuration (similar to .rubocop.yml)
# See https://doc.rust-lang.org/clippy/configuration.html for all options

# Cognitive complexity threshold (similar to RuboCop's complexity cops)
cognitive-complexity-threshold = 30

# Documentation requirements
missing-docs-in-crate-items = false

# Enum variant name threshold
enum-variant-name-threshold = 3

# Maximum number of lines for a single expression
single-char-binding-names-threshold = 4

# Maximum number of arguments for a function
too-many-arguments-threshold = 7

# Maximum number of lines for a function
too-many-lines-threshold = 100

# Type complexity threshold
type-complexity-threshold = 250

# Trivial copy threshold
trivial-copy-size-limit = 128

# Avoid certain lint groups that might be too strict initially
# You can enable these later as you get more comfortable with Rust
avoid-breaking-exported-api = false
