name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Similar to RuboCop checks in Ruby projects
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}

    - name: Check formatting (rustfmt)
      run: cargo fmt --all -- --check

    - name: Run Clippy (linting)
      run: cargo clippy --all-targets --all-features -- -D warnings

  # Build and test across OSes and toolchains
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
    steps:
    - uses: actions/checkout@v5

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}

    - name: Run tests
      run: cargo test --verbose

    - name: Build release
      run: cargo build --release --verbose

    - name: Smoke test (no token) --help and --version
      run: |
        cargo run -- --help
        cargo run -- --version

  # MSRV build job
  msrv:
    name: MSRV 1.78 Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install Rust (MSRV)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.78
        components: rustfmt, clippy
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    - name: Build
      run: cargo build --verbose

  # Security audit (similar to bundler-audit in Ruby)
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: rustsec/audit-check@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
